import { NextResponse } from 'next/server';
import { readFileSync } from 'fs';
import { join } from 'path';
import { getAdminClient, supabase } from '@/lib/supabase';

// Helper to determine the content directory
const contentDir = join(process.cwd(), 'content files');

function readMd(filename: string) {
  return readFileSync(join(contentDir, filename), 'utf-8');
}

const LECTURES = [
  { file: 'session-01-02.md', topic_slug: 'balance-of-payments', title: 'Balance of Payments (Sessions 1 & 2)', session_number: 1, sort_order: 1 },
  { file: 'session-03-04.md', topic_slug: 'history-trade-mercantilism', title: 'History of Trade & Mercantilism (Sessions 3 & 4)', session_number: 3, sort_order: 1 },
  { file: 'session-05-07.md', topic_slug: 'basis-for-trade', title: 'Basis for Trade: Smith, Ricardo & H-O Model (Sessions 5–7)', session_number: 5, sort_order: 1 },
  { file: 'session-08-09.md', topic_slug: 'empirical-trade-theories', title: 'Empirical & Alternate Trade Theories (Sessions 8 & 9)', session_number: 8, sort_order: 1 },
  { file: 'session-10.md', topic_slug: 'gains-terms-of-trade', title: 'Gains from Trade & Terms of Trade (Session 10)', session_number: 10, sort_order: 1 },
  { file: 'session-11-12.md', topic_slug: 'tariffs-quotas-trade-policy', title: 'Tariffs, Quotas & Trade Policy (Sessions 11 & 12)', session_number: 11, sort_order: 1 },
  { file: 'session-13-14.md', topic_slug: 'capital-flows-crises', title: 'Capital Flows & Crises (Sessions 13 & 14)', session_number: 13, sort_order: 1 },
  { file: 'session-15-16.md', topic_slug: 'exchange-rates-open-economy', title: 'Exchange Rates & Open Economy Macro (Sessions 15–16)', session_number: 15, sort_order: 1 },
  { file: 'session-17-18.md', topic_slug: 'exchange-rates-open-economy', title: 'Exchange Rates & Open Economy Macro (Sessions 17–18)', session_number: 17, sort_order: 2 },
];

const QUESTIONS = [
  // Short Answer
  { topic_slug: 'history-trade-mercantilism', question_text: 'Which of the following would be considered an accurate representation of the Mercantilist view regarding trade?\n\na) Balance exports and imports\nb) Send exports but do not import\nc) Send imports but do not export\nd) Merchants must have the right to import only', model_answer: '**Correct Answer: (b) — Send exports but do not import**\n\nMercantilism holds that a nation\'s wealth is measured by its stock of gold and silver. To accumulate these, a nation must export more than it imports — running a perpetual trade surplus. The core philosophy is **"Beggar thy trade partner"** — export as much as possible, restrict imports as much as possible.\n\nOptions (a), (c), and (d) are incorrect because mercantilism explicitly opposed balanced trade and was hostile to imports.', question_type: 'short_answer', marks: 1, difficulty: 'easy' },
  { topic_slug: 'basis-for-trade', question_text: "Lapland's production technology: Wool = 1.5 units/labour hour, Meat = 2 units/labour hour. If Lapland is isolated, what is the exchange rate for 1 unit of Meat (in terms of Wool)?\n\na) 3 Wool\nb) 0.75 Wool\nc) 2 Wool\nd) 1.5 Wool", model_answer: '**Correct Answer: (b) — 0.75 Wool**\n\nIn an isolated economy, the exchange rate between goods equals their **opportunity cost**.\n\nTo produce 1 unit of Meat, Lapland needs 1/2 labour hour. In that same 1/2 hour, Lapland could have produced: 1.5 × (1/2) = **0.75 units of Wool**.\n\nTherefore: **1 Meat = 0.75 Wool**\n\n*Alternative (labour theory of value):*\n- 1 unit of Meat requires 1/2 hour of labour\n- 1 unit of Wool requires 2/3 hour of labour\n- Exchange rate = (labour per Meat) / (labour per Wool) = (1/2) / (2/3) = **0.75 Wool per Meat** ✓', question_type: 'short_answer', marks: 1, difficulty: 'medium' },
  { topic_slug: 'basis-for-trade', question_text: 'Factor endowments:\n\n| Country | Labour | Land | Labour/Land Ratio |\n|---|---|---|---|\n| Galicia | 40 | 6 | 6.67 |\n| Crimea | 90 | 8 | 11.25 |\n| Donbass | 130 | 12 | 10.83 |\n\nWhich country is relatively labour-abundant per Heckscher-Ohlin theory?\n\na) Galicia\nb) Crimea\nc) Donbass\nd) None', model_answer: '**Correct Answer: (b) — Crimea**\n\nUnder H-O theory, **factor abundance is defined in relative (ratio) terms**, not absolute terms. Even though Donbass has the most labour (130), what matters is the Labour/Land ratio:\n\n- Galicia: 40/6 = **6.67**\n- Crimea: 90/8 = **11.25** ← highest\n- Donbass: 130/12 = **10.83**\n\nCrimea has the **highest Labour/Land ratio** → it is relatively most labour-abundant. H-O predicts Crimea will export the **labour-intensive** good and import the land-intensive good.', question_type: 'short_answer', marks: 1, difficulty: 'easy' },
  { topic_slug: 'basis-for-trade', question_text: "As per Ricardo's comparative advantage theory, which of the following must definitely be true for a country to export Good A (when it also produces Good B)?\n\n(i) Opportunity cost in terms of other goods must be low\n(ii) Relative price of A to B is higher\n(iii) Relative labour hours in producing Good A is lower\n(iv) Wages paid for Good A are higher\n\na) (ii) and (iii) only\nb) (i) and (iii) only\nc) (i) and (ii) only\nd) (ii) and (iv) only", model_answer: "**Correct Answer: (b) — (i) and (iii) only**\n\nRicardo's comparative advantage is based on:\n- **(i) Low opportunity cost:** A country exports a good when its opportunity cost is lower than its trading partner's. **TRUE** — this is the very definition of comparative advantage.\n- **(iii) Lower relative labour hours:** Fewer labour hours per unit of A relative to B (compared to your partner) = comparative advantage in A. **TRUE** — structural basis of Ricardo's model.\n\n**(ii) is NOT necessarily true:** The higher relative price of A is an *outcome* of trade, not a necessary pre-condition in Ricardo's real model.\n\n**(iv) is NOT true:** Higher wages for Good A workers have no role in Ricardo's real (non-monetary) model.", question_type: 'short_answer', marks: 1, difficulty: 'medium' },
  { topic_slug: 'basis-for-trade', question_text: 'India has labour abundance. Footwear is labour-intensive; auto manufacturing is capital-intensive. Trade opens — India imports footwear (prices fall), exports autos (prices rise). In the long run, per H-O and factor price equalization (assuming labour/capital are mobile across sectors), what happens to labour in India?\n\na) Labour better off as they move to auto sector\nb) Labour worse off even as they remain in footwear sector\nc) Labour better off as they remain in footwear sector\nd) Labour worse off even as they move to auto sector', model_answer: '**Correct Answer: (d) — Labour worse off even as they move to auto sector**\n\nThis tests the **Stolper-Samuelson Theorem** — the distributional implication of H-O:\n\n- India is labour-abundant → comparative advantage in labour-intensive goods (footwear)\n- When trade opens, the price of the labour-intensive good (footwear) **falls**\n- Stolper-Samuelson: a fall in the price of the labour-intensive good leads to a fall in the **real wage across ALL sectors**\n- Workers who move to the auto sector still face lower real wages because factor prices equalise economy-wide\n\n**Key insight:** Factor price equalisation is economy-wide, not sector-specific. All workers lose from the fall in the labour-intensive good\'s price, regardless of which sector they work in.', question_type: 'short_answer', marks: 1, difficulty: 'hard' },
  { topic_slug: 'gains-terms-of-trade', question_text: "Demand for toys: pre-trade price P, post-trade price P' (P' < P — trade lowers price for importing country). What is the net gain/loss of consumer surplus due to open trade?\n\na) Loss — Area of Triangle IPA\nb) Gain — Area of Rectangle 0PAQ\nc) Loss — Area of trapezium QABQ'\nd) Gain — Area of trapezium P'ABP", model_answer: "**Correct Answer: (d) — Gain — Area of trapezium P'ABP**\n\nWhen the price falls from P to P' due to trade:\n- Consumer surplus increases because consumers pay a lower price\n- The **gain in consumer surplus** = area between old price P and new lower price P', under the demand curve\n- This is a **trapezium** (since the demand curve slopes downward) bounded by the two price levels and the demand curve points A and B\n- Area = **P'ABP**\n\nThe answer is a *gain* (not a loss) because the price has fallen — consumers are better off.", question_type: 'short_answer', marks: 1, difficulty: 'medium' },
  { topic_slug: 'gains-terms-of-trade', question_text: "In the same diagram (pre-trade price P, post-trade price P', P' < P), what is the total revenue for both domestic and foreign manufacturers after open trade?\n\na) Area of rectangle 0P'BQ'\nb) Area of rectangle 0PAQ\nc) Area of trapezium QABQ'\nd) Area of trapezium P'ABP'", model_answer: "**Correct Answer: (a) — Area of rectangle 0P'BQ'**\n\nTotal revenue = **Price × Quantity** = P' × Q'\n\n- Post-trade price = P' (lower than pre-trade P)\n- Post-trade quantity demanded = Q' (larger than pre-trade Q, because lower price stimulates more consumption)\n- Total revenue = Area of **rectangle from origin to P' on price axis and Q' on quantity axis** = **0P'BQ'**\n\nNote: This total revenue is split between domestic producers (who supply less at lower P') and foreign producers who supply the imports.", question_type: 'short_answer', marks: 1, difficulty: 'easy' },
  { topic_slug: 'history-trade-mercantilism', question_text: "General Dynamics (defence manufacturer) approaches the US government to enact policies protecting their business against foreign competition. How would you categorise this action?\n\na) Gaining comparative advantage (Ricardian principles)\nb) Gaining domestic market share (political economy principles)\nc) Gaining protection for domestic and foreign markets (mercantilist principles)\nd) Gaining absolute advantage (Smith)", model_answer: '**Correct Answer: (c) — Mercantilist principles**\n\nGeneral Dynamics seeking government protection against foreign competition in both domestic and foreign markets is quintessentially **mercantilist**:\n- Using **state power** to protect merchant/industrial interests\n- Seeking to **restrict foreign competition** (mercantilist protectionism)\n- Seeking to **promote own exports** (mercantilist export promotion)\n- This reflects the "intimacy between State authority and merchant interest" described in class\n\nOptions (a) and (d) are wrong — both Ricardo and Smith argued *against* protectionism. Option (b) understates the action — it goes beyond domestic market share to include influencing government policy for foreign market access (the classic mercantilist agenda).', question_type: 'short_answer', marks: 1, difficulty: 'medium' },
  { topic_slug: 'basis-for-trade', question_text: 'Data for Marsland and Venusland:\n\n| | Marsland | Venusland |\n|---|---|---|\n| Wine (workers per bottle) | 15 | 10 |\n| Cheese (workers per kg) | 10 | 4 |\n\nEach country has 30 million workers. Who has absolute advantage in Wine and Cheese?\n\na) Marsland — Wine; Venusland — Cheese\nb) Marsland — Cheese; Venusland — Wine\nc) Marsland — Wine; Marsland — Cheese\nd) Venusland — Wine; Venusland — Cheese', model_answer: '**Correct Answer: (d) — Venusland has absolute advantage in BOTH goods**\n\nAbsolute advantage = fewer workers needed per unit = more output per worker:\n\n| Good | Marsland | Venusland | Better? |\n|---|---|---|---|\n| Wine | 15 workers/bottle | 10 workers/bottle | **Venusland** |\n| Cheese | 10 workers/kg | 4 workers/kg | **Venusland** |\n\nVenusland is more productive in both goods. This is the classic setup for demonstrating **comparative advantage** — even though Marsland has absolute *disadvantage* in everything, trade can still be mutually beneficial.', question_type: 'short_answer', marks: 1, difficulty: 'easy' },
  { topic_slug: 'basis-for-trade', question_text: 'Using the Marsland/Venusland data (Wine: Marsland 15 workers/bottle, Venusland 10; Cheese: Marsland 10 workers/kg, Venusland 4), what are the limits for the international price ratio P_Wine/P_Cheese for mutually beneficial trade?\n\na) 15/10 < x < 4/10\nb) 10/15 < x < 4/10\nc) 10/15 < x < 10/4\nd) 15/10 < x < 10/4', model_answer: '**Correct Answer: (d) — 15/10 < P_Wine/P_Cheese < 10/4**\n\n**Step 1: Find each country\'s domestic opportunity cost of Wine (in terms of Cheese):**\n\n**Marsland:**\n- To produce 1 Wine: need 15 workers\n- Those 15 workers could make 15/10 = **1.5 kg Cheese**\n- So P_Wine/P_Cheese = **1.5** in Marsland\n\n**Venusland:**\n- To produce 1 Wine: need 10 workers\n- Those 10 workers could make 10/4 = **2.5 kg Cheese**\n- So P_Wine/P_Cheese = **2.5** in Venusland\n\n**Comparative advantage:**\n- Marsland\'s opportunity cost for Wine (1.5) < Venusland\'s (2.5) → **Marsland exports Wine**\n- Venusland exports Cheese\n\n**Range for mutually beneficial trade:** Lower limit (Marsland\'s OC) < World Price < Upper limit (Venusland\'s OC)\n```\n15/10 < P_Wine/P_Cheese < 10/4\n1.5 < P_Wine/P_Cheese < 2.5\n```', question_type: 'short_answer', marks: 1, difficulty: 'hard' },

  // Long Answer
  { topic_slug: 'empirical-trade-theories', question_text: 'Compute the RCA (Revealed Comparative Advantage) index for each good and identify in which goods India has comparative advantage.\n\n| Good | India Exports (X_ij) | ROW Exports (X_wj) |\n|---|---|---|\n| Wine | 5 | 20 |\n| Cheese | 8 | 4 |\n| Tomatoes | 12 | 13 |\n| Apples | 13 | 35 |\n\nFormula: RCA_ij = (X_ij / X_wj) / (ΣX_i / ΣX_w)', model_answer: '**Step 1: Calculate total exports**\n- India total: 5 + 8 + 12 + 13 = **38**\n- World total (India + ROW): (5+20) + (8+4) + (12+13) + (13+35) = 25+12+25+48 = **110**\n\n**Step 2: India\'s overall export share**\n- 38/110 = **0.3455**\n\n**Step 3: RCA for each good**\n\n| Good | India | World | India\'s commodity share | RCA |\n|---|---|---|---|---|\n| Wine | 5 | 25 | 5/25 = 0.200 | 0.200 ÷ 0.3455 = **0.58** |\n| Cheese | 8 | 12 | 8/12 = 0.667 | 0.667 ÷ 0.3455 = **1.93** ✓ |\n| Tomatoes | 12 | 25 | 12/25 = 0.480 | 0.480 ÷ 0.3455 = **1.39** ✓ |\n| Apples | 13 | 48 | 13/48 = 0.271 | 0.271 ÷ 0.3455 = **0.78** |\n\n**Step 4: Conclusion**\n- **Cheese (RCA ≈ 1.93 > 1)** → India has revealed comparative advantage ✓\n- **Tomatoes (RCA ≈ 1.39 > 1)** → India has revealed comparative advantage ✓\n- Wine (0.58): No advantage\n- Apples (0.78): No advantage\n\n**Interpretation:** Balassa\'s RCA index reveals comparative advantage from actual trade data. RCA > 1 means India\'s share of world exports in that commodity exceeds its overall share of world exports — indicating specialisation and comparative advantage.', question_type: 'long_answer', marks: 5, difficulty: 'medium' },
  { topic_slug: 'basis-for-trade', question_text: 'Part (a): What does Heckscher-Ohlin theory predict about low-skilled wages in a low-skill labour-abundant economy when trade opens? (2.5 marks)\n\nPart (b): What mechanism counteracts this prediction in practice? Is there a problem with labour mobility across sectors? (2.5 marks)', model_answer: '**Part (a) — H-O prediction on low-skilled wages:**\n\nAccording to the **Heckscher-Ohlin theorem** and its distributional extension, the **Stolper-Samuelson theorem**:\n\n1. A labour-abundant country has comparative advantage in **labour-intensive goods** (e.g., garments, footwear). When trade opens, it exports these and imports capital-intensive goods.\n\n2. As the price of the exported (labour-intensive) good rises, demand for **low-skilled labour** increases. Stolper-Samuelson states this causes the **real wage of low-skilled workers to rise** — economy-wide, not just in the export sector.\n\n3. **Predicted outcome:** H-O/Stolper-Samuelson predicts **wages of low-skilled workers should rise** and inequality should *decrease* in labour-abundant developing countries when they open to trade.\n\n---\n\n**Part (b) — Counteracting mechanism and labour mobility:**\n\nThe counteracting mechanism is the **skill-biased nature of outsourcing**:\n\n1. Multinationals offshore to developing countries but hire **skilled** workers (who can operate technology and meet quality standards)\n2. Foreign-owned factories pay **up to 40% higher wages** than local firms (OECD data)\n3. Working with foreign technology **raises productivity of skilled workers** → even higher wage demands\n4. **Unskilled rural workers** do not access these opportunities — their productivity stagnates\n\n**Result:** Trade raises wages of *skilled* workers while unskilled wages stagnate → inequality *rises* (opposite of H-O prediction)\n\n**On labour mobility — the problem:**\n\nStolper-Samuelson assumes **perfect factor mobility across sectors**. In reality, this fails because:\n1. **Geographic immobility:** Rural unskilled workers face high migration costs\n2. **Skills mismatch:** Export factories require minimum skill levels\n3. **Network barriers:** Urban formal sector requires social connections rural migrants lack\n4. **Cost of migration:** Upfront costs unaffordable for the poorest workers\n\n**Conclusion:** When factor mobility is blocked, gains from trade do not reach unskilled workers. Skilled workers capture the gains, causing rising within-country inequality — even as H-O theory predicted the opposite.', question_type: 'long_answer', marks: 5, difficulty: 'hard' },
];

export async function POST() {
  try {
    const admin = getAdminClient();

    // 1. Fetch topics
    const { data: topics, error: topicErr } = await supabase.from('topics').select('id, slug');
    if (topicErr) throw new Error('Failed to fetch topics');
    
    const topicBySlug = Object.fromEntries(topics.map((t: any) => [t.slug, t.id]));
    
    // 2. Insert Lectures
    let lecturesInserted = 0;
    for (const lec of LECTURES) {
      const topic_id = topicBySlug[lec.topic_slug];
      if (!topic_id) continue;

      const { data: existing } = await supabase.from('lectures')
        .select('id').eq('topic_id', topic_id).eq('title', lec.title).maybeSingle();
      if (existing) continue;

      let notes_md = null;
      try { notes_md = readMd(lec.file); } catch (e) { console.warn(`Could not read file: ${lec.file}`); }

      const { error } = await admin.from('lectures').insert({
        topic_id, title: lec.title, session_number: lec.session_number, notes_md, sort_order: lec.sort_order,
      });
      if (!error) lecturesInserted++;
    }

    // 3. Insert Questions
    let questionsInserted = 0;
    for (const q of QUESTIONS) {
      const topic_id = topicBySlug[q.topic_slug];
      if (!topic_id) continue;

      const { data: existing } = await supabase.from('questions')
        .select('id').eq('topic_id', topic_id).ilike('question_text', q.question_text.slice(0, 80) + '%').maybeSingle();
      if (existing) continue;

      const { error } = await admin.from('questions').insert({
        topic_id, question_text: q.question_text, model_answer: q.model_answer, question_type: q.question_type, marks: q.marks, difficulty: q.difficulty,
      });
      if (!error) questionsInserted++;
    }

    return NextResponse.json({ success: true, lecturesInserted, questionsInserted });
  } catch (error: any) {
    console.error(error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
